### ISSUE TITLE
all Crons are activated when the module is reset

### ISSUE THREAD

**Issue by rb26** [Martin-Laclaustra/CronAlarms#2]
on esp 12th and esp1s:
when powering on or when reset, all Crons are activated, they are then active according to their programming
cordialement RB
(nb goo traduction)

**Comment by Martin-Laclaustra** [comment]
Sorry, but I do not understand the problem. After a reset, you need to set current time before using the library.
(btw, what is your native language?)

**Comment by Martin-Laclaustra** [comment]
Closed for absence of response with further details.

**Comment by mendicm** [comment]
Hi! I think that I'm facing the same problem. I'm using an ESP32 with the follow code:

```c
#include <WiFi.h>
#include <Time.h>
#include "CronAlarms.h"

#define WIFI_SSID "SSID"
#define WIFI_PASSWORD "PASSWORD"
void setup() {
  Serial.begin(115200);
  Serial.print("Connecting…"); 
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println();

  configTime(3600, 0, "pool.ntp.org", "time.nist.gov");  // CET
  Cron.create("30 49 0 * * *", timer, false);
}

void loop() {
  struct tm timeinfo;
  getLocalTime(&timeinfo);
  Serial.println(&timeinfo, "%A, %B %d %Y %H:%M:%S");
  Cron.delay(1000);
}

void timer() {
  Serial.println("TIMER EXECUTED!!!");
}
```

And this is the output:

```
Connecting…...
Sunday, November 22 2020 00:49:23
TIMER EXECUTED!!!
Sunday, November 22 2020 00:49:24
Sunday, November 22 2020 00:49:25
Sunday, November 22 2020 00:49:26
Sunday, November 22 2020 00:49:27
Sunday, November 22 2020 00:49:28
Sunday, November 22 2020 00:49:29
TIMER EXECUTED!!!
Sunday, November 22 2020 00:49:30
Sunday, November 22 2020 00:49:31
Sunday, November 22 2020 00:49:32
Sunday, November 22 2020 00:49:33
```

As you can see I set a cron at 0:49:30 but it was executed two times, one at the first loot after boot and the good one at the desired time. I'm doing somethig wrong of there is some kind of bug?

Thanks!

**Comment by Martin-Laclaustra** [comment]
There is a known reason.
Any action for setting time that supposes a "jump forward in time" triggers all alarms that were "left behind".

In your case that happens when the automatic NTP service updates time from "0 time" to current time. With current release, the only strategy is to set the alarms after the correct time is set.

See https://github.com/Martin-Laclaustra/CronAlarms/issues/8#issuecomment-706585070

I think that `configTzTime()` might force time retrieval (but I do not think that it is blocking while time is received):
```
configTzTime("CET-1CEST,M3.5.0,M10.5.0/3", "pool.ntp.org");
```
You could force it with blocking code in `setup()` (this is untested draft code):
```
    time_t now;
    struct tm info;
    time(&now);
    localtime_r(&now, &info);
    while(info->tm_year < (2016 - 1900)) {
        delay(10);
        time(&now);
        localtime_r(&now, &info);
    }
```

I have a new version almost ready that allows temporarily disabling alarms while setting time. This is not relevant in your case but it might be for people using RTCs that require setting the time.
I will try to get a couple of examples ready for that release too.

Please report back.

**Comment by mendicm** [comment]
I see… all has sense now! Very appreciated for your help, thank you.
