### ISSUE TITLE
display project update

### ISSUE THREAD

**Issue by ghost** [Martin-Laclaustra/CronAlarms#6]
Sorry to post here again but I can't see anywhere else I could post ... 

Curious to hear how your display driver is going - it sounded very interesting - my hand is up to do testing.

I was thinking of the possibility of creating a github project with the goal of unifying all the latest ideas in esp32 display/sound technology, supporting VGA/PAL/NTSC, - MIT licensed, supporting both esp32 and esp32-s2.  All new code, not drawn from other projects. Especially important that the door would be fully open to contributors to join the project as equal project leaders and do direct commits - the idea being to build a team/community of active contributors. There's several really great esp32 video and sound projects on github right now, but the license and ongoing activity level of the original author varies from project to project. What do you think - is that something you'd find interesting?

**Comment by Martin-Laclaustra** [comment]
@bootrino your comment is interesting, but please stop polluting this other repository.
Please write where I invited you last time:
https://github.com/bitluni/ESP32Lib/issues/50

Bitluni has not been available for the last months because of personal questions. I am not very available either for the next month. I stalled on the project because I wanted to reach consensus with bitluni. I hope that things can resume later on.

Please write in that issue and we will plan for actions (but right now delayed 1 month).
